USE [MyOsago]
GO

/****** Object:  Table [dbo].[Osago]    Script Date: 20.01.2020 14:10:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Osago](
	[Id] [nchar](15) NOT NULL,
	[IdInsurant] [nchar](20) NOT NULL,
	[IdOwner] [nchar](20) NOT NULL,
	[IdCar] [nchar](20) NOT NULL,
	[IdFaces] [nchar](20) NOT NULL,
	[BegDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[ConDate] [date] NOT NULL,
	[Prize] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[IdCar] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Osago]  WITH CHECK ADD FOREIGN KEY([IdCar])
REFERENCES [dbo].[Cars] ([Id])
GO

ALTER TABLE [dbo].[Osago]  WITH CHECK ADD FOREIGN KEY([IdInsurant])
REFERENCES [dbo].[Insurant] ([Id])
GO

ALTER TABLE [dbo].[Osago]  WITH CHECK ADD FOREIGN KEY([IdOwner])
REFERENCES [dbo].[Owner] ([Id])
GO
